### ISSUE TITLE
Better "Broken" and "Variant" tag in the database

### ISSUE THREAD

**Issue by psml-imeji** [robx/puzzledb#24]
Those tags should not be applied if only a few users clicked them. As many puzzles has been tagged "Broken" even those puzzles are prefectly soluble.

**Comment by robx** [comment]
It might be worth considering raising the number of votes required to accept the broken tag. But could you share some examples? Note that a puzzle having a solution is not enough to make it not "broken" -- if there are multiple solutions, it is also broken.

**Comment by psml-imeji** [comment]
Mistakely broken: 
https://puzz.link/p?heyawake/18/18/9h8qcr6aapiij3kkqq5an5al6adtijlckpbp6ee9jprmuetlj7ddpj8sgq74og0f7nvs000fvo03pv7gnv01vjvne0vg67g7o0v004uvv040hnehgs3hvfu047v0i1g1h100h03h1l1i1j2g1g4l1i2h1h2i11i0k1l0g0h21j
https://puzz.link/p?nurikabe/10/10/.p.l.i.p.p.p.p.p.i.l.q
(Sorry for only 2 links, because I removed those broken tags on my side.)

**Comment by robx** [comment]
Yeah, can confirm that your idea of broken matches mine. :) (I checked a couple more in the database.)

I've updated the threshold for the "broken" tag for now, so that there needs to be more of a consensus before a puzzle is marked broken. For "variant", I think we're fine, since the puzzle will still show up by default, and plenty of people will mark it not-variant when they see this.
