### ISSUE TITLE
Add puzz.link/db stats

### ISSUE THREAD

**Issue by edderiofer** [robx/puzzledb#9]
So that users can see how many of each type of puzzle there are (including how many puzzles are in the current search), average solve times for a puzzle, etc.

**Comment by robx** [comment]
A general "off-line" stats page should be straightforward to add. I'm less enthusiastic about live stats, particularly counts of current searches. Generally counting search results of a database query is much more expensive than just finding the next page, since it requires looking at the whole result set. (Unless it's precomputed, but we can't really do that for a general "current search", particularly if it includes user-specific information such as number of solved vs unsolved.)

**Comment by robx** [comment]
There's a global stats page (presently count of puzzles by source and by difficulty; would be easy to add more). I'll close this one and leave #8 for the user stats.

**Comment by mwoghiren** [comment]
@robx I'd love to see more db stats—in particular, puzzle counts grouped by type and difficulty (so that e.g. one could see how many difficulty 2 Yajilin puzzles there are).

**Comment by mwoghiren** [comment]
(The above example would also be accomplished via #20, but having that info on a stats page could be useful too.)
